weights_path: "/home/misa/Documents/KIE-MISA/api-cvext/src/core/checkpoints/en_ptocr_v3_det_infer.pth"

net:
  Backbone: 
    scale: 0.5
    disable_se: True
  Neck:
    out_channels: 96
    use_residual: True
  Head:
    k: 50

pre_process_list:
  - DetResize:
      limit_side_len: 960
      limit_type: 'max'
  - NormalizeImage:
      std:
        - 0.229
        - 0.224
        - 0.225
      mean:
        - 0.485
        - 0.456
        - 0.406
      scale: '1./255'
      order: 'hwc'
  - ToCHWImage: 
  - KeepKeys:
      keep_keys:
        - image
        - shape

postprocess_params:
  thresh: 0.3
  box_thresh: 0.7
  max_candidates: 1000
  unclip_ratio: 2.0
  use_dilation: False
  score_mode: 'fast'